### ISSUE TITLE
Destination storage location of files are not on the same file system

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/dync#3]
This issue will most likely lead to an unresponsive behaviour of the server script, as during the os.rename() process the file has in fact to be copied and removed from the temporary destination to the target destination, which is a physically separated device mounted on the receiving file system.

**Comment by aseyboldt** [comment]
It will raise an exception: `OSError: Invalid cross-device link`.

**Comment by sven1103** [comment]
Ok, but the issue remains, that the physical storage of the dropboxes will always be on a different file system. That means one still has to do a full copy of the uploaded file, which I would like to avoid. I am currently figuring out, on which machine the dropboxes are located can be accessed directly.

**Comment by aseyboldt** [comment]
We don't want to copy the files. But the only thing we need is that the temporary dir is on the same fs than the dropboxes. `UploadFile` already has a `tmp_prefix` option. We should expose that in `Storage` and then make an appropriate tempdir somewhere on the dropbox filesystem.

**Comment by sven1103** [comment]
well, that is a good idea

**Comment by sven1103** [comment]
Uploaded files have to land on same file system as the openBis dropboxes, then we are good to go.
