### ISSUE TITLE
Assign the correct target dropbox

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/dync#5]
Currently, dync will try to upload files in either the default dir, given in the config, or move them into a target project-related directory, if meta-data provided. Both target directories are not connected to openBis.

For pre-registered data, containing a valid barcode in their filename, the correct dropbox has to be determined. This is dependent on the file-type or/and the client that uploaded the file.

Code can be used from the dropboxhandler. 

Customer can be identified by the client ID from the public/private key-pair that was used.

**Comment by sven1103** [comment]
Adrian pointed out code that can be used: https://github.com/qbicsoftware/dropboxhandler/blob/master/dropboxhandler/dropboxhandler.py#L114

**Comment by sven1103** [comment]
Also, the assignment logic shall be in `_destination_from_meta()`in storage.py

**Comment by aseyboldt** [comment]
Fixed in #9
