### ISSUE TITLE
Check value for 'passthrough' directive.

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/dync#6]
Currently, a user can pass a key:value pair like `-k passthrough:/home/whoever/.bashrc` which leads to manipulation of the target dir.

**Comment by sven1103** [comment]
Now, '/', '\', '.' and space is not allowed anymore as argument.

**Comment by aseyboldt** [comment]
If you don't want to allow paths, it's better to use a whitelist than a blacklist. Maybe just allow alphanumerics and '_'
